### ISSUE TITLE
Deprecate PyPI packages

### ISSUE THREAD

**Issue by raprasad** [opendifferentialprivacy/whitenoise-core-python#68]
**Tasks** 

- [ ] Add deprecation notes to the SmartNoise Core PyPI Package
- [ ] Change the README text to prominently indicate deprecation and link to the OpenDP library
- [ ] Update the README to change any email references from  `@opendp.io` to `@opendp.org`, e.g. on the README page
- [ ] Binaries: __These may remain the same__ and are still in use by other groups including Microsoft
- [ ] `setup.py` - Add a deprecation warning -- but _do not_ raise an exception as the packages are still in use.

**PyPI Page**
- https://pypi.org/project/opendp-smartnoise-core/

**Related Crate issue**
- https://github.com/opendp/smartnoise-core/issues/363
